# SPDX-FileCopyrightText: 2023 Genome Research Ltd.
#
# SPDX-License-Identifier: MIT

from sqlalchemy import (
    BigInteger,
    Boolean,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    String,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.ext.associationproxy import association_proxy
from sqlalchemy.orm import mapped_column, relationship
from sqlalchemy.sql import expression

from tolqc.schema.base import Base, LogBase
from tolqc.schema.folder_models import HasFolder


class Allocation(Base):
    __tablename__ = 'allocation'

    id = mapped_column(Integer, primary_key=True)  # noqa: A003
    project_id = mapped_column(String, ForeignKey('project.project_id'))
    data_id = mapped_column(String, ForeignKey('data.data_id'))
    is_primary = mapped_column(Boolean)

    UniqueConstraint('project_id', 'data_id')
    UniqueConstraint('data_id', 'is_primary')

    project = relationship('Project', back_populates='data_assn')
    data = relationship('Data', back_populates='project_assn')


class BarcodeMetrics(Base, HasFolder):
    __tablename__ = 'barcode_metrics'

    id = mapped_column(Integer, primary_key=True)  # noqa: A003
    data_id = mapped_column(String, ForeignKey('data.data_id'))
    qc_id = mapped_column(Integer)  # QCDict pass|fail ?

    # Is this a foreign key to the species table?
    species_match_top = mapped_column(String)

    species_match_identity = mapped_column(Float)
    species_match_barcode = mapped_column(String)

    data = relationship('Data', back_populates='barcode_metrics')


class CategoryDict(Base):
    __tablename__ = 'category_dict'

    @classmethod
    def get_id_column_name(cls):
        return 'category'

    category = mapped_column(String, primary_key=True)
    description = mapped_column(String)


class Centre(Base):
    __tablename__ = 'centre'

    id = mapped_column(Integer, primary_key=True)  # noqa: A003
    name = mapped_column(String)
    hierarchy_name = mapped_column(String)

    run = relationship('Run', back_populates='centre')


class ChemistryDict(Base):
    __tablename__ = 'chemistry_dict'

    @classmethod
    def get_id_column_name(cls):
        return 'chemistry'

    chemistry = mapped_column(String, primary_key=True)
    description = mapped_column(String)


class Data(LogBase, HasFolder):
    __tablename__ = 'data'

    @classmethod
    def get_id_column_name(cls):
        return 'data_id'

    data_id = mapped_column(String, primary_key=True)
    study_id = mapped_column(Integer, ForeignKey('study.study_id'))
    category = mapped_column(String, ForeignKey('category_dict.category'))
    sample_id = mapped_column(String, ForeignKey('sample.sample_id'))
    library_id = mapped_column(String, ForeignKey('library.library_id'))
    accession_id = mapped_column(String, ForeignKey('accession.accession_id'))
    run_id = mapped_column(String, ForeignKey('run.run_id'))
    processed = mapped_column(Integer, index=True)
    tag1_id = mapped_column(String)
    tag2_id = mapped_column(String)
    pcr_adapter_id = mapped_column(String)
    date = mapped_column(DateTime(timezone=True))
    lims_qc = mapped_column(String, ForeignKey('qc_dict.qc_state'))
    auto_qc = mapped_column(String, ForeignKey('qc_dict.qc_state'))
    qc = mapped_column(String, ForeignKey('qc_dict.qc_state'))
    visibility = mapped_column(
        String,
        ForeignKey('visibility_dict.visibility'),
        default='Always',
        index=True,
    )
    reads = mapped_column(BigInteger)
    bases = mapped_column(BigInteger)
    read_length_mean = mapped_column(Float)
    read_length_n50 = mapped_column(BigInteger)

    # From PacBio stats file generated by tolpipe:
    bases_a = mapped_column(BigInteger)
    bases_c = mapped_column(BigInteger)
    bases_g = mapped_column(BigInteger)
    bases_t = mapped_column(BigInteger)
    read_length_longest = mapped_column(Integer)
    read_length_shortest = mapped_column(Integer)

    # From parsing PacBio pbmarkdup log generated by tolpipe:
    reads_duplicated = mapped_column(BigInteger)

    # From parsing .trim.summary.json files
    reads_discarded = mapped_column(BigInteger)
    reads_trimmed = mapped_column(BigInteger)
    bases_removed = mapped_column(BigInteger)

    sample = relationship('Sample', back_populates='data')
    library = relationship('Library', back_populates='data')
    accession = relationship('Accession', back_populates='data')
    run = relationship('Run', back_populates='data')
    files = relationship('File', back_populates='data')
    barcode_metrics = relationship('BarcodeMetrics', back_populates='data')
    mapping_metrics = relationship('MappingMetrics', back_populates='data')
    tiara_metrics = relationship('TiaraMetrics', back_populates='data')
    study = relationship('Study', back_populates='data')

    project_assn = relationship('Allocation', back_populates='data')
    projects = association_proxy('project_assn', 'project')

    dataset_assn = relationship('DatasetElement', back_populates='data')
    datasets = association_proxy('dataset_assn', 'dataset')


class DataSubmission(LogBase):
    __tablename__ = 'data_submission'

    @classmethod
    def get_id_column_name(cls):
        return 'data_id'

    data_id = mapped_column(String, ForeignKey('data.data_id'), primary_key=True)

    study_accession_id = mapped_column(
        String,
        ForeignKey('accession.accession_id'),
    )
    sample_accession_id = mapped_column(
        String,
        ForeignKey('accession.accession_id'),
    )
    experiment_accession_id = mapped_column(
        String,
        ForeignKey('accession.accession_id'),
    )
    run_accession_id = mapped_column(
        String,
        ForeignKey('accession.accession_id'),
    )
    analysis_accession_id = mapped_column(
        String,
        ForeignKey('accession.accession_id'),
    )

    submission_time = mapped_column(DateTime(timezone=True), index=True)

    study_accession = relationship(
        'Accession',
        primaryjoin='DataSubmission.study_accession_id == Accession.accession_id',
        back_populates='study_submissions',
    )
    sample_accession = relationship(
        'Accession',
        primaryjoin='DataSubmission.sample_accession_id == Accession.accession_id',
        back_populates='sample_submissions',
    )
    experiment_accession = relationship(
        'Accession',
        primaryjoin='DataSubmission.experiment_accession_id == Accession.accession_id',
        back_populates='experiment_submissions',
    )
    run_accession = relationship(
        'Accession',
        primaryjoin='DataSubmission.run_accession_id == Accession.accession_id',
        back_populates='run_submissions',
    )
    analysis_accession = relationship(
        'Accession',
        primaryjoin='DataSubmission.analysis_accession_id == Accession.accession_id',
        back_populates='analysis_submissions',
    )


class File(Base):
    __tablename__ = 'file'

    id = mapped_column(Integer, primary_key=True)  # noqa: A003
    data_id = mapped_column(String, ForeignKey('data.data_id'))
    name = mapped_column(String, index=True)
    relative_path = mapped_column(String)
    remote_path = mapped_column(String, index=True)
    public_path = mapped_column(String)
    insdc_path = mapped_column(String)
    size_bytes = mapped_column(BigInteger)
    md5 = mapped_column(String)
    file_type = mapped_column(String, ForeignKey('file_type_dict.file_type'))
    has_methylation = mapped_column(Boolean, index=True)
    has_kinetics = mapped_column(Boolean, index=True)
    sam_tags = mapped_column(JSONB)

    data = relationship('Data', back_populates='files')


class FileTypeDict(Base):
    __tablename__ = 'file_type_dict'

    @classmethod
    def get_id_column_name(cls):
        return 'file_type'

    file_type = mapped_column(String, primary_key=True)
    description = mapped_column(String)


class Library(Base):
    __tablename__ = 'library'

    @classmethod
    def get_id_column_name(cls):
        return 'library_id'

    library_id = mapped_column(String, primary_key=True)
    library_type_id = mapped_column(
        String,
        ForeignKey('library_type.library_type_id'),
    )
    lims_id = mapped_column(Integer)

    data = relationship('Data', back_populates='library')
    library_type = relationship('LibraryType', back_populates='library')


class LibraryType(Base):
    __tablename__ = 'library_type'

    @classmethod
    def get_id_column_name(cls):
        return 'library_type_id'

    library_type_id = mapped_column(String, primary_key=True)
    hierarchy_name = mapped_column(String)
    default_category = mapped_column(String)
    reporting_category = mapped_column(String, index=True)
    kit = mapped_column(String)
    enzymes = mapped_column(String)
    cut_sites = mapped_column(String)
    is_pcr = mapped_column(Boolean, server_default=expression.false(), index=True)

    library = relationship('Library', back_populates='library_type')


class Location(Base):
    __tablename__ = 'location'

    @classmethod
    def get_id_column_name(cls):
        return 'location_id'

    location_id = mapped_column(Integer, primary_key=True)
    path = mapped_column(String, index=True)

    species = relationship('Species', back_populates='location')
    specimens = relationship('Specimen', back_populates='location')


class MappingMetrics(Base, HasFolder):
    __tablename__ = 'mapping_metrics'

    id = mapped_column(Integer, primary_key=True)  # noqa: A003
    data_id = mapped_column(String, ForeignKey('data.data_id'), nullable=False)
    assembly_id = mapped_column(Integer, ForeignKey('assembly.assembly_id'))
    pipeline_id = mapped_column(
        Integer,
        ForeignKey('pipeline.pipeline_id'),
    )

    # From parsing Illumina samtools stats file generated on mapped bam by
    # tolpipe:
    reads_duplicated = mapped_column(BigInteger)

    # From Illumina samtools stats file generated by NPG, but copied and
    # parsed by tolpipe (may be able to get a number for PacBio for this
    # too):
    average_quality = mapped_column(Float)

    # From Illumina samtools stats file generated on mapped bam by tolpipe:
    bases_duplicated = mapped_column(BigInteger)
    bases_mapped = mapped_column(BigInteger)
    bases_mapped_cigar = mapped_column(BigInteger)
    bases_trimmed = mapped_column(BigInteger)
    error_rate = mapped_column(Float)
    insert_size_average = mapped_column(Float)
    insert_size_standard_deviation = mapped_column(Float)
    inward_oriented_pairs = mapped_column(BigInteger)
    mismatches = mapped_column(BigInteger)
    outward_oriented_pairs = mapped_column(BigInteger)
    pairs_on_different_chromosomes = mapped_column(BigInteger)
    pairs_with_other_orientation = mapped_column(BigInteger)
    reads_mapped = mapped_column(BigInteger)
    reads_mapped_and_paired = mapped_column(BigInteger)
    reads_mq0 = mapped_column(BigInteger)
    reads_properly_paired = mapped_column(BigInteger)
    reads_unmapped = mapped_column(BigInteger)

    data = relationship('Data', back_populates='mapping_metrics')
    assembly = relationship('Assembly', back_populates='mapping_metrics')
    pipeline = relationship(
        'Pipeline',
        back_populates='mapping_metrics',
    )


class Offspring(Base):
    __tablename__ = 'offspring'

    id = mapped_column(Integer, primary_key=True)  # noqa: A003
    specimen_id = mapped_column(String, ForeignKey('specimen.specimen_id'))
    offspring_specimen_id = mapped_column(String, ForeignKey('specimen.specimen_id'))

    UniqueConstraint('specimen_id', 'offspring_specimen_id')

    parent = relationship(
        'Specimen',
        foreign_keys=[specimen_id],
        back_populates='parent_assn',
    )
    offspring = relationship(
        'Specimen',
        foreign_keys=[offspring_specimen_id],
        back_populates='offspring_assn',
    )


class PacbioRunMetrics(Base, HasFolder):
    __tablename__ = 'pacbio_run_metrics'

    @classmethod
    def get_id_column_name(cls):
        return 'run_id'

    run_id = mapped_column(String, ForeignKey('run.run_id'), primary_key=True)
    movie_minutes = mapped_column(Integer)
    binding_kit = mapped_column(String)
    sequencing_kit = mapped_column(String)
    sequencing_kit_lot_number = mapped_column(String)
    cell_lot_number = mapped_column(String)
    include_kinetics = mapped_column(String)
    loading_conc = mapped_column(Float)
    control_num_reads = mapped_column(Integer)
    control_read_length_mean = mapped_column(Float)
    control_concordance_mean = mapped_column(Float)
    control_concordance_mode = mapped_column(Float)
    local_base_rate = mapped_column(Float)
    polymerase_read_bases = mapped_column(BigInteger)
    polymerase_num_reads = mapped_column(Integer)
    polymerase_read_length_mean = mapped_column(Float)
    polymerase_read_length_n50 = mapped_column(Integer)
    insert_length_mean = mapped_column(Float)
    insert_length_n50 = mapped_column(Integer)
    unique_molecular_bases = mapped_column(BigInteger)
    productive_zmws_num = mapped_column(Integer)
    p0_num = mapped_column(Integer)
    p1_num = mapped_column(Integer)
    p2_num = mapped_column(Integer)
    adapter_dimer_percent = mapped_column(Float)
    short_insert_percent = mapped_column(Float)
    hifi_read_bases = mapped_column(BigInteger)
    hifi_num_reads = mapped_column(Integer)
    hifi_read_length_mean = mapped_column(Integer)
    hifi_read_quality_median = mapped_column(Integer)
    hifi_number_passes_mean = mapped_column(Float)
    hifi_low_quality_read_bases = mapped_column(BigInteger)
    hifi_low_quality_num_reads = mapped_column(Integer)
    hifi_low_quality_read_length_mean = mapped_column(Integer)
    hifi_low_quality_read_quality_median = mapped_column(Integer)
    hifi_barcoded_reads = mapped_column(Integer)
    hifi_bases_in_barcoded_reads = mapped_column(BigInteger)

    run = relationship('Run', back_populates='pacbio_run_metrics')


class Platform(Base):
    __tablename__ = 'platform'

    id = mapped_column(Integer, primary_key=True)  # noqa: A003
    name = mapped_column(String)
    model = mapped_column(String)

    run = relationship('Run', back_populates='platform')


class Project(LogBase):
    __tablename__ = 'project'

    @classmethod
    def get_id_column_name(cls):
        return 'project_id'

    project_id = mapped_column(String, primary_key=True)
    name = mapped_column(String)
    description = mapped_column(String)
    accession_id = mapped_column(String, ForeignKey('accession.accession_id'))
    symlink_template = mapped_column(String)

    accession = relationship('Accession', back_populates='projects')
    data_assn = relationship('Allocation', back_populates='project')
    data = association_proxy('data_assn', 'data')
    default_studies = relationship('Study', back_populates='default_project')


class QCDict(Base):
    __tablename__ = 'qc_dict'

    @classmethod
    def get_id_column_name(cls):
        return 'qc_state'

    qc_state = mapped_column(String, primary_key=True)


class Run(Base):
    __tablename__ = 'run'

    @classmethod
    def get_id_column_name(cls):
        return 'run_id'

    run_id = mapped_column(String, primary_key=True)
    platform_id = mapped_column(Integer, ForeignKey('platform.id'))
    centre_id = mapped_column(Integer, ForeignKey('centre.id'))
    lims_id = mapped_column(String, index=True)
    element = mapped_column(String)
    instrument_name = mapped_column(String)
    start = mapped_column(DateTime(timezone=True))
    complete = mapped_column(DateTime(timezone=True))
    plex_count = mapped_column(Integer)
    chemistry = mapped_column(String, ForeignKey('chemistry_dict.chemistry'))

    data = relationship('Data', back_populates='run')
    platform = relationship('Platform', back_populates='run')
    centre = relationship('Centre', back_populates='run')
    pacbio_run_metrics = relationship('PacbioRunMetrics', back_populates='run')


class Sample(LogBase):
    __tablename__ = 'sample'

    @classmethod
    def get_id_column_name(cls):
        return 'sample_id'

    sample_id = mapped_column(String, primary_key=True)
    hierarchy_name = mapped_column(String)
    lims_id = mapped_column(Integer)
    specimen_id = mapped_column(String, ForeignKey('specimen.specimen_id'))
    accession_id = mapped_column(String, ForeignKey('accession.accession_id'))

    specimen = relationship('Specimen', back_populates='samples')
    accession = relationship('Accession', back_populates='samples')
    data = relationship('Data', back_populates='sample')


class Sex(Base):
    __tablename__ = 'sex'

    @classmethod
    def get_id_column_name(cls):
        return 'sex_id'

    sex_id = mapped_column(String, primary_key=True)
    description = mapped_column(String)

    specimens = relationship('Specimen', back_populates='sex')


class Species(LogBase):
    __tablename__ = 'species'

    @classmethod
    def get_id_column_name(cls):
        return 'species_id'

    species_id = mapped_column(String, primary_key=True)
    location_id = mapped_column(Integer, ForeignKey('location.location_id'))
    tolid_prefix = mapped_column(String, unique=True)
    common_name = mapped_column(String)
    taxon_id = mapped_column(Integer, index=True)
    family_taxon_id = mapped_column(Integer, index=True)
    taxon_family = mapped_column(String)
    taxon_order = mapped_column(String)
    taxon_phylum = mapped_column(String)
    taxon_group = mapped_column(String)
    genome_size = mapped_column(BigInteger)
    chromosome_number = mapped_column(Integer)
    data_accession_id = mapped_column(String, ForeignKey('accession.accession_id'))
    umbrella_accession_id = mapped_column(String, ForeignKey('accession.accession_id'))

    specimens = relationship('Specimen', back_populates='species')
    data_accession = relationship(
        'Accession',
        primaryjoin='Species.data_accession_id == Accession.accession_id',
        back_populates='data_species',
    )
    umbrella_accession = relationship(
        'Accession',
        primaryjoin='Species.umbrella_accession_id == Accession.accession_id',
        back_populates='umbrella_species',
    )

    location = relationship('Location', back_populates='species')
    metagenomes = relationship('Metagenome', back_populates='species')
    metagenome_bins = relationship('MetagenomeBin', back_populates='species')


class Specimen(LogBase):
    __tablename__ = 'specimen'

    @classmethod
    def get_id_column_name(cls):
        return 'specimen_id'

    specimen_id = mapped_column(String, primary_key=True)
    location_id = mapped_column(Integer, ForeignKey('location.location_id'))
    specimen_status_id = mapped_column(
        Integer,
        ForeignKey('specimen_status.specimen_status_id'),
    )
    species_id = mapped_column(String, ForeignKey('species.species_id'))
    epithet = mapped_column(String, index=True)
    taxon_id = mapped_column(Integer, index=True)
    lims_id = mapped_column(Integer)
    supplied_name = mapped_column(String, index=True)
    sts_specimen = mapped_column(String, index=True)
    sts_priority = mapped_column(Integer, index=True)
    category = mapped_column(String, ForeignKey('specimen_category_dict.category'))
    accession_id = mapped_column(String, ForeignKey('accession.accession_id'))
    sex_id = mapped_column(String, ForeignKey('sex.sex_id'))
    ploidy = mapped_column(String)
    karyotype = mapped_column(String)
    cobiont_specimen_id = mapped_column(String, ForeignKey('specimen.specimen_id'))
    assigned_user_id = mapped_column(Integer, ForeignKey('user.id'))

    species = relationship('Species', back_populates='specimens')
    samples = relationship('Sample', back_populates='specimen')
    sex = relationship('Sex', back_populates='specimens')
    accession = relationship('Accession', back_populates='specimens')

    status = relationship('SpecimenStatus', foreign_keys=[specimen_status_id])
    status_history = relationship(
        'SpecimenStatus',
        primaryjoin='Specimen.specimen_id == SpecimenStatus.specimen_id',
        back_populates='specimen',
    )

    location = relationship('Location', back_populates='specimens')

    parent_assn = relationship(
        'Offspring',
        primaryjoin='Specimen.specimen_id == Offspring.specimen_id',
        back_populates='parent',
    )
    offspring = association_proxy('parent_assn', 'offspring')

    offspring_assn = relationship(
        'Offspring',
        primaryjoin='Specimen.specimen_id == Offspring.offspring_specimen_id',
        back_populates='offspring',
    )
    parents = association_proxy('offspring_assn', 'parent')

    assemblies = relationship('Assembly', back_populates='specimen')
    metagenomes = relationship('Metagenome', back_populates='host_specimen')

    cobiont_of = relationship(
        'Specimen',
        primaryjoin='Specimen.cobiont_specimen_id == Specimen.specimen_id',
        back_populates='cobionts',
        remote_side=[specimen_id],
    )
    cobionts = relationship(
        'Specimen',
        primaryjoin='Specimen.specimen_id == Specimen.cobiont_specimen_id',
        back_populates='cobiont_of',
    )

    assignee = relationship(
        'User',
        primaryjoin='Specimen.assigned_user_id == User.id',
        back_populates='assigned_specimens',
    )


class SpecimenCategoryDict(Base):
    __tablename__ = 'specimen_category_dict'

    @classmethod
    def get_id_column_name(cls):
        return 'category'

    category = mapped_column(String, primary_key=True)
    description = mapped_column(String)


class SpecimenStatus(LogBase):
    __tablename__ = 'specimen_status'

    @classmethod
    def get_id_column_name(cls):
        return 'specimen_status_id'

    specimen_status_id = mapped_column(Integer, primary_key=True)
    specimen_id = mapped_column(
        String,
        ForeignKey('specimen.specimen_id'),
        nullable=False,
    )
    status_type_id = mapped_column(
        String,
        ForeignKey('specimen_status_type.status_type_id'),
        nullable=False,
    )
    status_time = mapped_column(DateTime(timezone=True), nullable=False)

    specimen = relationship(
        'Specimen',
        foreign_keys=[specimen_id],
        back_populates='status_history',
    )
    status_type = relationship('SpecimenStatusType', back_populates='statuses')


class SpecimenStatusType(Base):
    __tablename__ = 'specimen_status_type'

    @classmethod
    def get_id_column_name(cls):
        return 'status_type_id'

    status_type_id = mapped_column(String, primary_key=True)
    description = mapped_column(String)
    assign_order = mapped_column(Integer)

    statuses = relationship('SpecimenStatus', back_populates='status_type')


class Study(LogBase):
    __tablename__ = 'study'

    @classmethod
    def get_id_column_name(cls):
        return 'study_id'

    study_id = mapped_column(Integer, primary_key=True)
    name = mapped_column(String)
    auto_sync = mapped_column(Boolean, server_default=expression.true(), nullable=False)
    accession_id = mapped_column(String, ForeignKey('accession.accession_id'))
    default_project_id = mapped_column(String, ForeignKey('project.project_id'))

    accession = relationship('Accession', back_populates='studies')
    data = relationship('Data', back_populates='study')
    default_project = relationship('Project', back_populates='default_studies')


class TiaraMetrics(Base):
    __tablename__ = 'tiara_metrics'

    id = mapped_column(Integer, primary_key=True)  # noqa: A003
    data_id = mapped_column(String, ForeignKey('data.data_id'))
    division = mapped_column(String)
    reads = mapped_column(BigInteger)
    bases = mapped_column(BigInteger)
    read_length_n50 = mapped_column(Integer)

    UniqueConstraint('division', 'data_id')

    data = relationship('Data', back_populates='tiara_metrics')


class VisibilityDict(Base):
    __tablename__ = 'visibility_dict'

    @classmethod
    def get_id_column_name(cls):
        return 'visibility'

    visibility = mapped_column(String, primary_key=True)
    description = mapped_column(String)
