{{- if .Values.db.create_local }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tolqc-app.db.fullname" . }}
  labels:
    {{- include "tolqc-app.labels" . | nindent 4 }}
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
{{- end }}
