# SPDX-FileCopyrightText: 2021 Genome Research Ltd.
#
# SPDX-License-Identifier: MIT

include:
  - project: 'tol/tol-core'
    ref: main
    file: '/gitlab/main.yml'

stages:
  - lint
  - build
  - unit test
  - deploy
  - integration test

build-api:
  extends: .build-template
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ''
    PART: "tolqc-api"
    DOCKERFILE: "tolqc-api/Dockerfile"
    NAME: "tolqc-api"

build-ui:
  extends: .build-template
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ''
    PART: "tolqc-ui"
    DOCKERFILE: 'tolqc-ui/Dockerfile'
    NAME: "tolqc-ui"

test-unit:
  extends: .test-unit
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ''
    GIT_STRATEGY: none
    NAME: tolqc-api
    PART: tolqc-api

test-migrations:
  extends: .test-migrations
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ''
    GIT_STRATEGY: none
    NAME: tolqc-api

deploy-staging:
  extends: .auto-deploy
  environment:
    name: staging
    url: https://qc-staging.tol.sanger.ac.uk
  only:
    - staging

deploy-production:
  extends: .auto-deploy
  environment:
    name: production
    url: https://qc.tol.sanger.ac.uk/
  only:
    - production
  when: manual

deploy-qa:
  extends: .auto-deploy
  environment:
    name: qa
    url: http://qc-qa.tol.sanger.ac.uk
  only:
    - qa
    #REEEMOVE
    - sts-backport
