# SPDX-FileCopyrightText: 2022 Genome Research Ltd.
#
# SPDX-License-Identifier: MIT

include:
  - project: 'tol/tol-core'
    ref: '862e8b92de8a928c0c0320773db1e32d36cfd77f'
    file: '/gitlab/app.yml'

variables:
  APP_NAME: tolqc
  SERVICE_NAME: qc
