# SPDX-FileCopyrightText: 2021 Genome Research Ltd.
#
# SPDX-License-Identifier: MIT

include:
  - project: 'tol/tol-core'
    ref: main
    file: '/gitlab/main.yml'

stages:
  - lint
  - build
  - unit test
  - push
  - review
  - deploy
  - integration test
  - cleanup

build-api:
  extends: .build-template
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ''
    PART: "tolqc-api"
    DOCKERFILE: "tolqc-api/Dockerfile"
    NAME: "tolqc-api"

build-ui:
  extends: .build-template
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ''
    PART: "tolqc-ui"
    DOCKERFILE: 'tolqc-ui/Dockerfile'
    NAME: "tolqc-ui"

build-ui-test:
  extends: .build-template
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ''
    PART: "tolqc-ui"
    DOCKERFILE: 'tolqc-ui/Dockerfile.dev'
    NAME: "tolqc-ui-test"

test-ui:
  image: $DOCKER_IMAGE
  stage: unit test
  services:
    - name: $DIND_IMAGE
      alias: docker
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ''
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker run -e CI=true $CI_REGISTRY_IMAGE/tolqc-ui-test:$CI_COMMIT_SHA yarn test
  except:
    - qa
    - staging
    - production
  allow_failure: true

push-api:
  extends: .push-template
  variables:
    GIT_STRATEGY: none
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ''
    NAME: tolqc-api

push-ui:
  extends: .push-template
  variables:
    GIT_STRATEGY: none
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ''
    NAME: tolqc-ui

push-ui-test:
  extends: .push-template
  variables:
    GIT_STRATEGY: none
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ''
    NAME: tolqc-ui-test

deploy-qa:
  extends: .swarm-deploy-template
  environment:
    name: qa
    url: http://172.27.27.72:8000
  variables:
    DOCKER_HOST: "ssh://ubuntu@172.27.27.72"
    EXTRA_DEPLOY_FILES: ""
    STACK_NAME: tolqc
  script:
    - echo "Deployed to qa"
  only:
    - qa

deploy-staging:
  extends: .swarm-deploy-template
  environment:
    name: staging
    url: https://qc-staging.tol.sanger.ac.uk
  variables:
    DOCKER_HOST: "ssh://ubuntu@172.27.26.124"
    EXTRA_DEPLOY_FILES: "-c docker-compose.gitlab-logging.yml"
    STACK_NAME: tolqc
  script:
    - echo "Deployed to staging"
  only:
    - staging

deploy-production:
  extends: .swarm-deploy-template
  environment:
    name: production
    url: https://qc.tol.sanger.ac.uk/
  variables:
    DOCKER_HOST: "ssh://ubuntu@172.27.26.62"
    EXTRA_DEPLOY_FILES: "-c docker-compose.gitlab-logging.yml"
    STACK_NAME: tolqc
  script:
    - echo "Deployed to production"
  only:
    - production
  when: manual

test-api:
  extends: .swarm-deploy-template
  image: $DOCKER_IMAGE
  stage: integration test
  resource_group: testing
  services:
    - name: $DIND_IMAGE
      alias: docker
  environment:
    name: testing
    url: http://172.27.25.82:8000
  variables:
    DOCKER_HOST: "ssh://ubuntu@172.27.25.82"
    EXTRA_DEPLOY_FILES: "-c docker-compose.gitlab-test.yml"
    STACK_NAME: tolqc
  script:
    - sleep 60
    - docker exec $(docker ps -q -f name="tolqc_tolqc-api") 
      bash -c "pytest -v"
  except:
    - qa
    - staging
    - production


variables:
  AUTO_DEPLOY_IMAGE_VERSION: 'v2.25.0'

.auto-deploy:
  image: "registry.gitlab.com/gitlab-org/cluster-integration/auto-deploy-image:${AUTO_DEPLOY_IMAGE_VERSION}"
  dependencies: []

review:
  extends: .auto-deploy
  stage: review
  script:
    - auto-deploy check_kube_domain
    - auto-deploy download_chart
    - auto-deploy use_kube_context || true
    - auto-deploy ensure_namespace
    - auto-deploy initialize_tiller
    - auto-deploy create_secret
    - auto-deploy deploy
    - auto-deploy persist_environment_url
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://$CI_PROJECT_ID-$CI_ENVIRONMENT_SLUG.$KUBE_INGRESS_BASE_DOMAIN
    on_stop: stop_review
  artifacts:
    paths: [environment_url.txt, tiller.log]
    when: always
  rules:
    - if: '($CI_KUBERNETES_ACTIVE == null || $CI_KUBERNETES_ACTIVE == "") && ($KUBECONFIG == null || $KUBECONFIG == "")'
      when: never
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: never
    - if: '$REVIEW_DISABLED'
      when: never
    - if: '$CI_COMMIT_TAG || $CI_COMMIT_BRANCH'

stop_review:
  extends: .auto-deploy
  stage: cleanup
  variables:
    GIT_STRATEGY: none
  script:
    - auto-deploy use_kube_context || true
    - auto-deploy initialize_tiller
    - auto-deploy delete
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  allow_failure: true
  rules:
    - if: '($CI_KUBERNETES_ACTIVE == null || $CI_KUBERNETES_ACTIVE == "") && ($KUBECONFIG == null || $KUBECONFIG == "")'
      when: never
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: never
    - if: '$REVIEW_DISABLED'
      when: never
    - if: '$CI_COMMIT_TAG || $CI_COMMIT_BRANCH'
      when: manual

