# SPDX-FileCopyrightText: 2021 Genome Research Ltd.
#
# SPDX-License-Identifier: MIT

include:
  - project: 'tol/tol-core'
    ref: add-view-jobs
    file: '/gitlab/main.yml'

stages:
  - lint
  - build
  - unit test
  - deploy
  - integration test

build-api:
  extends: .build-template
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ''
    PART: "tolqc-api"
    DOCKERFILE: "tolqc-api/Dockerfile"
    NAME: "tolqc-api"

build-ui:
  extends: .build-template
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ''
    PART: "tolqc-ui"
    DOCKERFILE: 'tolqc-ui/Dockerfile'
    NAME: "tolqc-ui"

deploy-staging:
  extends: .auto-deploy
  environment:
    name: staging
    url: https://qc-staging.tol.sanger.ac.uk
  only:
    - staging

deploy-production:
  extends: .swarm-deploy-template
  environment:
    name: production
    url: https://qc.tol.sanger.ac.uk/
  variables:
    DOCKER_HOST: "ssh://ubuntu@172.27.26.62"
    EXTRA_DEPLOY_FILES: "-c docker-compose.gitlab-logging.yml"
    STACK_NAME: tolqc
  script:
    - echo "Deployed to production"
  only:
    - production
  when: manual

deploy-qa:
  extends: .auto-deploy
  variables:
    CI_COMMIT_SHA: "7f07f6fe0f9f8dd2a750d83c9afe2a1270088f64"
  environment:
    name: qa
    url: http://qc-qa.tol.sanger.ac.uk
  only:
    - qa
    - helm-test-edward #TODO remove this! 
