# SPDX-FileCopyrightText: 2022 Genome Research Ltd.
#
# SPDX-License-Identifier: MIT

include:
  - project: 'tol/tol-core'
    ref: 'ee33104fabcf2c1140a6d3584784173240bb5672' # TODO put back to fixed version
    file: '/gitlab/app.yml'

variables:
  APP_NAME: tolqc
  SERVICE_NAME: qc
