# SPDX-FileCopyrightText: 2022 Genome Research Ltd.
#
# SPDX-License-Identifier: MIT

include:
  - project: 'tol/tol-core'
    ref: v1.3.14
    file: '/gitlab/app.yml'

variables:
  APP_NAME: tolqc
  SERVICE_NAME: qc
  TZ: "Europe/London"

  DISABLE_UI_LINT: "true"
