# SPDX-FileCopyrightText: 2022 Genome Research Ltd.
#
# SPDX-License-Identifier: MIT

include:
  - project: 'tol/tol-core'
    ref: v1.1.0
    file: '/gitlab/main.yml'

variables:
  APP_NAME: 'tolqc'
  SERVICE_NAME: 'qc'