channels:
  # Define conda channels here.
  - conda-forge

dependencies:
  # Define conda packages here.
  # If available, always prefer the conda version of a package.
  # Installation will be faster and more efficient.
  # https://anaconda.org/search
  - python=3.9.6

  - pip3=22.3.1
  - pip3:
      # Define pip packages here.
      # https://pypi.org/
      - rpaframework==23.3.0 # https://rpaframework.org/releasenotes.html