# SPDX-FileCopyrightText: 2021 Genome Research Ltd.
#
# SPDX-License-Identifier: MIT

# Used for deploying a logging container in Staging/Production
version: '3'
services: 
  tolqc-logspout:
    image: gliderlabs/logspout:latest
    networks:
      - tolqc
    volumes:
      - /etc/hostname:/etc/host_hostname:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      $SYSLOG_URI
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.20'
          memory: 256M
        reservations:
          cpus: '0.10'
          memory: 128M
