# SPDX-FileCopyrightText: 2022 Genome Research Ltd.
#
# SPDX-License-Identifier: MIT

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tolqc-app.fullname" . }}
  labels:
    {{- include "tolqc-app.labels" . | nindent 4 }}
data:
  POSTGRES_USER: {{ .Values.db.user }}
  POSTGRES_PASSWORD: {{ .Values.db.password }}
  POSTGRES_DB: {{ .Values.db.name }}
  POSTGRES_HOST: {{ .Values.db.host }}
  POSTGRES_PORT: "{{ .Values.db.port }}"
  DB_URI: {{ .Values.db.uri }}
  TOLQC_API_LOCATION: {{ .Values.api.url }}
  FLASK_ENV: {{ .Values.flask.env }}
  BACKUP_S3_URI: {{ .Values.s3.uri }}
  BACKUP_S3_ACCESS_KEY: {{ .Values.s3.access_key }}
  BACKUP_S3_SECRET_KEY: {{ .Values.s3.secret_key }}
  BACKUP_S3_BUCKET: {{ .Values.s3.bucket }}
  BACKUP_S3_SECURE: {{ .Values.s3.secure }}
  BACKUP_SCHEDULE: {{ .Values.backup.schedule }}
  RESTORE_FILE_PREFIX: {{ .Values.restore.prefix }}
