{{- if .Values.ingress.enabled -}}
{{- $fullName := include "tolqc-app.fullname" . -}}
{{- $uiName := include "tolqc-app.ui.fullname" . -}}
{{- $uiPort := .Values.ui.service.port -}}
{{- $apiName := include "tolqc-app.api.fullname" . -}}
{{- $apiPort := .Values.api.service.port -}}
{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "tolqc-app.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .host | quote }}
      http:
        paths:
          - path: /api/v1
            pathType: Prefix
            backend:
              service:
                name: {{ $apiName }}
                port:
                  number: {{ $apiPort }}
          - path: /swaggerui
            pathType: Prefix
            backend:
              service:
                name: {{ $apiName }}
                port:
                  number: {{ $apiPort }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $uiName }}
                port:
                  number: {{ $uiPort }}
{{- end }}
