{{- if .Values.ingress.enabled -}}
{{- $dbName := include "tolqc-app.db.fullname" . -}}
{{- $dbPort := include "tolqc-app.db.port" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: ingress-nginx
data:
  {{ $dbPort }}: "{{ .Release.Namespace }}/{{ $dbName }}:{{ $dbPort }}"
{{- end }}
