apiVersion: v1
kind: ConfigMap
metadata:
  name: alembic-{{ .Release.Revision}} # change this back!!!
  labels:
    {{- include "tolqc-app.labels" . | nindent 4 }}
data:
  DB_URI: {{ include "tolqc-app.db.uri" . }}
