apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tolqc-app.alembic.fullname" . }}
  labels:
    {{- include "tolqc-app.labels" . | nindent 4 }}
data:
  DB_URI: {{ include "tolqc-app.db.uri" . }}
