# SPDX-FileCopyrightText: 2022 Genome Research Ltd.
#
# SPDX-License-Identifier: MIT

FROM python:3.12-slim

ENV FLASK_ENV=development
ENV PYTHONDONTWRITEBYTECODE=1
ENV VIRTUAL_ENV=/app

WORKDIR "$VIRTUAL_ENV"
RUN python3 -m venv "$VIRTUAL_ENV"
ENV PATH="$VIRTUAL_ENV/bin:$PATH"
RUN pip3 --no-cache-dir install --upgrade pip

COPY ./app app
COPY ./pyproject.toml .
COPY ./README.md .
RUN pip3 --no-cache-dir install . 'tolqc-api[test]'

WORKDIR "$VIRTUAL_ENV/app/test"
