# SPDX-FileCopyrightText: 2022 Genome Research Ltd.
#
# SPDX-License-Identifier: MIT

# This is used for local development only.
FROM gitlab-registry.internal.sanger.ac.uk/tol/tol-core/web-base-dev:1.0.4

COPY ./app/package.json ./

RUN yarn install

COPY ./app/ ./
