# SPDX-FileCopyrightText: 2022 Genome Research Ltd.
#
# SPDX-License-Identifier: MIT

# This is used for local development only.
FROM node:14.15.4-alpine

RUN npm install react-scripts@2.1.8 -g --silent

WORKDIR /usr/src/app

RUN echo \"@tol:registry\" \"https://gitlab.internal.sanger.ac.uk/api/v4/projects/3596/packages/npm/\" >> .yarnrc

ENV PATH /usr/src/app/node_modules/.bin:$PATH

VOLUME ["/packages"]

COPY ./app/package.json ./

RUN yarn install

COPY ./app/ ./

RUN yarn global add yalc;

CMD if [ -d /packages/tol-ui ]; \
then cd /packages/tol-ui; \
yarn build; \
yalc push --scripts --update --replace; \
cd /usr/src/app; \
yalc link @tol/tol-ui; \
fi; \
yarn start
