# SPDX-FileCopyrightText: 2021 Genome Research Ltd.
#
# SPDX-License-Identifier: MIT

# This is used for local development only.
FROM node:14.15.4-alpine

RUN npm install react-scripts@2.1.8 -g --silent

WORKDIR /usr/src/app

ENV PATH /usr/src/app/node_modules/.bin:$PATH

COPY ./app/package.json ./app/yarn.lock ./

RUN yarn install

COPY ./app/ ./

CMD yarn start